template
atherdon/newsletters pull request #382
Opened 2021-05-23 08:38 UTC by coder-do

@atherdon 
#380 

сделал - вышло вроде 
![template](https://user-images.githubusercontent.com/68124376/119253717-95badb80-bbc3-11eb-9607-4358b015bab7.png)

Только вот лист айтемы все с 1 начинаютя думаю ручками подменить нумерацию надо

- ссылки на фото из гитлаба еще aws не добавляли

2021-05-23 10:11 UTC, atherdon commented
title это первый заголовок рассылки (**it's not safe**)
насчет списка - пока сделайте коммент в основном таске, я подумал что делать.

2021-05-23 10:13 UTC, atherdon commented
для того, чтобы решить проблему со списками, у нас есть [эта задача](https://github.com/atherdon/markdown-to-email/issues/448), но чтобы ее начать - мне нужно закончить переносить callbackas

2021-05-23 10:14 UTC, atherdon requested changes
темплейт внутри идет с ошибкой. вы использовали wwworking-version для его генерации?

2021-05-23 10:22 UTC, coder-do commented
> темплейт внутри идет с ошибкой. вы использовали wwworking-version для его генерации?

Да - а в чем ошибка?

2021-05-23 12:21 UTC, atherdon commented
посмотрите со строки 450

2021-05-23 12:44 UTC, coder-do commented
да увидел (
я в wworking-version делал - может в мейн ветке надо делать ?

2021-05-24 10:12 UTC, atherdon commented
@coder-do надо тогда разобраться нам будет почему full-template падает в ветке wworking

2021-05-24 10:16 UTC, atherdon commented
main просто нихрена не стабильный сейчас. мы же его перекраиваем полностью. и я давно если честно не запускал тесты, чтобы точно понимать что генератор работает для наших случаев

2021-05-25 15:43 UTC, atherdon commented
я пока закрою этот пул - а когда пофиксим wworking-branch - протестим на другом кейсе

2021-05-25 15:43 UTC, closed without merging